### ISSUE TITLE
a typo in your the build section of Readme

### ISSUE THREAD

**Issue by Ilaner2000** [sharplab/epub-translator#121]
Hi,
It is a great tool, thank you. However, I found the following typo will cause the build to fail
./gradlew quarkusBuild -Dquarkus.package.type=uber-jar

it shall be 
 ./gradlew quarkusBuild -D quarkus.package.type=uber-jar

**Comment by ynojima** [comment]
Fixed in https://github.com/sharplab/epub-translator/commit/bff504f8d8c7af8b33eeb96178e48a8c74e438dd
