### ISSUE TITLE
ChatGPT API integration

### ISSUE THREAD

**Issue by odcpw** [sharplab/epub-translator#137]
Hi! is it possible to add an integration of the ChatGPT API?

**Comment by ynojima** [comment]
What kind of integration do you think?

**Comment by odcpw** [comment]
Instead of going to Deepl, have the translator call ChatGPT with a prompt like "please translate this to" $LANGUAGE. see https://github.com/yihong0618/bilingual_book_maker

**Comment by ynojima** [comment]
Is ChatGPT more fluent than DeepL? 
"Preserving XML tags in the texts" is a requirement for the translation engine, but as far as I know, ChatGPT doesn't support it natively.

**Comment by astromaddie** [comment]
In my experience, ChatGPT is less accurate at translations than DeepL, so I would not recommend this change.
