### ISSUE TITLE
Failed to load config value of type class java.lang.String for: ePubTranslator.deepL.apiKey

### ISSUE THREAD

**Issue by oogleabcd** [sharplab/epub-translator#157]
Hello. I do not know why it has to be like this. I've tried both formats to no avail.This error occurs anyway：
Failed to load config value of type class java.lang.String for: ePubTranslator.deepL.apiKey
----
First
`apiKey: <my key>`
second
`apiKey: "my key"`

**Comment by ynojima** [comment]
Have you done this configuration? : https://github.com/sharplab/epub-translator#configuration

**Comment by ynojima** [comment]
The working directory (current directory) to run `epub-translator-runner.jar` should be `epub-translator-runner.jar` container directory. In your case, it should be `epub` directory.

**Comment by oogleabcd** [comment]
> The working directory (current directory) to run `epub-translator-runner.jar` should be `epub-translator-runner.jar` container directory. In your case, it should be `epub` directory.

Hello, maybe the Chinese path is causing the problem. When I changed to D disk, this error no longer occurs. Now there is a new error: DeepL returns a 403 error. My API KEY is correct, and I can also log in to DeepL.
