### ISSUE TITLE
Lines sometimes fail to translate and are formatted in the epub as "I'm not sure what to make about that." etc

### ISSUE THREAD

**Issue by astromaddie** [sharplab/epub-translator#39]
I translated an epub novel and fairly frequently, lines completely fail to translate. The text that it "fills in" seems to be error headers from DeepL like "If you'd like to know more about the product, you can contact us on the web." or "I'm not sure what to make about that." Could you add some error detection to retry lines that fail to translate?

**Comment by astromaddie** [comment]
More precise wording of the message I've seen, now that I'm looking at it on my Kindle, is "In the event that you have any questions regarding where and how to use the internet, you can contact us at the web site."

This tool is really fantastic, by the way! I'm still not very good at reading kanji, so this helps me practise reading a Japanese novel and seeing more written sentences.

**Comment by astromaddie** [comment]
I think I'll have to try redoing the translation of this epub... I've come across a section where almost every paragraph is filled with lines like this:

"In the event that you have any questions regarding where and the best way to get in touch with us, please do not hesitate to contact us. I'm not sure what to make of it. In the event that you have any questions regarding where and the best way to get in touch with us, please do not hesitate to contact us."

**Comment by lulalala** [comment]
@astromaddie I am curious that, if you paste the paragraph into the deepL web interface, would the translation be the same? 

I just wonder if retrying would make a difference, and whether this message is from deepL's mistranslation.
