### ISSUE TITLE
Feature Request: Continue translation process after error

### ISSUE THREAD

**Issue by sashage** [sharplab/epub-translator#4]
It would be great to have a flag to continue the translation process after it failed.

I just ran a translation and hit the cost control limit in DeepL which stopped the script.
The result is that I had the run the entire book through DeepL again and pay twice for the quota.

This would be a great addition.

**Comment by ynojima** [comment]
I understand you want to reduce the DeepL cost when the translation fails.
#62 addresses the issue by reusing the translated texts.
