### ISSUE TITLE
Feature Request: Support for furigana

### ISSUE THREAD

**Issue by astromaddie** [sharplab/epub-translator#40]
Japanese books that contain furigana fail to translate, not just because the furigana is present in <rt>furigana</rt> tags, but also because the kanji that contain furigana are wrapped in separate <span> tags. The best workaround is to edit the epub xhtml files in something like Calibre, remove all <rt>.*?</rt>, and then add separate regex searches to remove spans that contain one character and replace them with contents of the single-character span. This works, but is time consuming and loses the furigana.

I realise you probably designed this with the intention of going the other direction, English to Japanese, but could you consider adding support to filter out furigana when translating a line?

**Comment by ynojima** [comment]
Thank you for your feedback, and sorry for late response.
I don't have enough time to tackle this issue now, but I'd like to try when I have time.

**Comment by astromaddie** [comment]
Thank you for the response!
I'm happy to hear you'll consider tackling this issue.
Looking forward to seeing an update some time in the future!

**Comment by rtega** [comment]
The simplest thing to do would be to simply remove the furigana before sending it for translation to deepl with a regexp like this:
`s/<ruby><rb>(.*?)<\/rb>〘<rt>.*?<\/rt>〙<\/ruby>/\1/g`
